Proxy Auth fix
unRob/sip-client pull request #6
Opened 2018-01-20 06:07 UTC by iguana

digest.signRequest modifies headers in the request object passed in to it, so that's what should be sent back. This fix was tested with Twilio SIP Domain.

2018-01-22 20:15 UTC, unRob requested changes
Thanks for this PR! I have this project in very poor shape, so I really appreciate your work!

2018-01-22 20:15 UTC, unRob commented on src/sip-client.coffee
>  			response = digest.signRequest([challenge], request, msg, {user: @options.user, realm: challenge.realm, password:@options.password})
Should we remove this assignment too?

2020-05-15 09:38 UTC, VasylDmytruk commented
This fix helped me too.

2020-05-15 18:23 UTC, unRob commented
@VasylDmytruk thanks for testing! I've updated the PR with my suggestion, sorry for the delay @iguana !

2020-05-15 18:23 UTC, merged